
#include <xed/xed-app.h>
#include <xed/xed-app-activatable.h>
#include <xed/xed-commands.h>
#include <xed/xed-debug.h>
#include <xed/xed-document.h>
#include <xed/xed-encodings-combo-box.h>
#include <xed/xed-file-chooser-dialog.h>
#include <xed/xed-message.h>
#include <xed/xed-message-bus.h>
#include <xed/xed-message-type.h>
#include <xed/xed-notebook.h>
#include <xed/xed-panel.h>
#include <xed/xed-progress-info-bar.h>
#include <xed/xed-searchbar.h>
#include <xed/xed-statusbar.h>
#include <xed/xed-tab.h>
#include <xed/xed-view.h>
#include <xed/xed-view-activatable.h>
#include <xed/xed-window.h>
#include <xed/xed-window-activatable.h>
