
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __XED_ENUM_TYPES_H__
#define __XED_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS
/* Enumerations from "/home/nick/xed-vala-plugin/xed/build/../xed/xed-debug.h" */
#define XED_TYPE_DEBUG_SECTION	(xed_debug_section_get_type())
GType xed_debug_section_get_type	(void) G_GNUC_CONST;
/* Enumerations from "/home/nick/xed-vala-plugin/xed/build/../xed/xed-searchbar.h" */
#define XED_TYPE_SEARCH_MODE	(xed_search_mode_get_type())
GType xed_search_mode_get_type	(void) G_GNUC_CONST;
/* Enumerations from "/home/nick/xed-vala-plugin/xed/build/../xed/xed-tab.h" */
#define XED_TYPE_TAB_STATE	(xed_tab_state_get_type())
GType xed_tab_state_get_type	(void) G_GNUC_CONST;
/* Enumerations from "/home/nick/xed-vala-plugin/xed/build/../xed/xed-window.h" */
#define XED_TYPE_WINDOW_STATE	(xed_window_state_get_type())
GType xed_window_state_get_type	(void) G_GNUC_CONST;
G_END_DECLS

#endif /* __XED_ENUM_TYPES_H__ */

/* Generated data ends here */

