/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#pragma once

#include <glib-object.h>

G_BEGIN_DECLS

/* BOOLEAN:VOID (../xed/xed-marshal.list:1) */
extern
void xed_marshal_BOOLEAN__VOID (GClosure     *closure,
                                GValue       *return_value,
                                guint         n_param_values,
                                const GValue *param_values,
                                gpointer      invocation_hint,
                                gpointer      marshal_data);

/* BOOLEAN:OBJECT (../xed/xed-marshal.list:2) */
extern
void xed_marshal_BOOLEAN__OBJECT (GClosure     *closure,
                                  GValue       *return_value,
                                  guint         n_param_values,
                                  const GValue *param_values,
                                  gpointer      invocation_hint,
                                  gpointer      marshal_data);

/* VOID:BOOLEAN (../xed/xed-marshal.list:3) */
#define xed_marshal_VOID__BOOLEAN	g_cclosure_marshal_VOID__BOOLEAN

/* VOID:BOOLEAN,POINTER (../xed/xed-marshal.list:4) */
extern
void xed_marshal_VOID__BOOLEAN_POINTER (GClosure     *closure,
                                        GValue       *return_value,
                                        guint         n_param_values,
                                        const GValue *param_values,
                                        gpointer      invocation_hint,
                                        gpointer      marshal_data);

/* VOID:BOXED,BOXED (../xed/xed-marshal.list:5) */
extern
void xed_marshal_VOID__BOXED_BOXED (GClosure     *closure,
                                    GValue       *return_value,
                                    guint         n_param_values,
                                    const GValue *param_values,
                                    gpointer      invocation_hint,
                                    gpointer      marshal_data);

/* VOID:OBJECT (../xed/xed-marshal.list:6) */
#define xed_marshal_VOID__OBJECT	g_cclosure_marshal_VOID__OBJECT

/* VOID:POINTER (../xed/xed-marshal.list:7) */
#define xed_marshal_VOID__POINTER	g_cclosure_marshal_VOID__POINTER

/* VOID:OBJECT,BOXED,FLAGS (../xed/xed-marshal.list:8) */
extern
void xed_marshal_VOID__OBJECT_BOXED_FLAGS (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);

/* VOID:OBJECT,BOXED,INT,BOOLEAN (../xed/xed-marshal.list:9) */
extern
void xed_marshal_VOID__OBJECT_BOXED_INT_BOOLEAN (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* VOID:UINT,POINTER (../xed/xed-marshal.list:10) */
#define xed_marshal_VOID__UINT_POINTER	g_cclosure_marshal_VOID__UINT_POINTER

/* VOID:UINT64,UINT64 (../xed/xed-marshal.list:11) */
extern
void xed_marshal_VOID__UINT64_UINT64 (GClosure     *closure,
                                      GValue       *return_value,
                                      guint         n_param_values,
                                      const GValue *param_values,
                                      gpointer      invocation_hint,
                                      gpointer      marshal_data);

/* VOID:VOID (../xed/xed-marshal.list:12) */
#define xed_marshal_VOID__VOID	g_cclosure_marshal_VOID__VOID

/* VOID:INT,INT (../xed/xed-marshal.list:13) */
extern
void xed_marshal_VOID__INT_INT (GClosure     *closure,
                                GValue       *return_value,
                                guint         n_param_values,
                                const GValue *param_values,
                                gpointer      invocation_hint,
                                gpointer      marshal_data);


G_END_DECLS
